other
initializeAll

	Autoconsumo initializeCache.
	CIIU initializeCache.
	Autoconsumo initializeCache.
	FuenteEnergia initializeCache.
	Instrumento initializeCache.
	Moneda initializeCache.
	NombreMedidaEficienciaEnergetica initializeCache.
	Rol initializeCache.
	Sector initializeCache.
	TarifaReferencia initializeCache.
	Usuario initializeCache.
	Representante initializeCache.
	RepresentanteESCO initializeCache.
	Empresa initializeCache.
	Persona initializeCache.
	ESCO initializeCache.