*MIEM_Templates
form_valores_escenarios_3

	^'<?xml version="1.0" encoding="UTF-8"?><form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
                    <internal-section>
                        <s>jut0Ge4xjTLepKzg</s>
                        <k>y7lQXjV8GOaXS4id</k>
                        <uuid>59b238d2-f0f0-4504-a021-160bf0906b32</uuid>
                        <oop>12511485441</oop>
                        <assignmentOop>12511487489</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>juan@MIEM</username>
                        <rol>[Empresa]</rol>
                        <processId>3941178460</processId>
                    </section-11>
                    <section-1>
                        <section-1-iteration>
                            <medidaUsoPrincipal>',UsoMedida validNames randomPeek key,'</medidaUsoPrincipal>
                            <medidaFechaInicioOperacion>2019-05-06</medidaFechaInicioOperacion>
                            <medidaEsOperativa>true</medidaEsOperativa>
                            <medidaMoneda>usd</medidaMoneda>
                            <medidaInversionTotal>', (#(10000 20000 30000 40000) randomPeek) printString,'</medidaInversionTotal>
                            <medidaVidaUtil>', (#(1 2 3 4 5 6) randomPeek) printString,'</medidaVidaUtil>
                            <medidaGradoImplementacion>',(#('en-diagnostico' 'en-produccion' 'en-implementacion') randomPeek),'</medidaGradoImplementacion>
                            <section-2>
                                <section-2-iteration>
                                    <escSinMedidaFuenteEnergia>', FuenteEnergia mappedCodigos keys asOrderedCollection randomPeek,'</escSinMedidaFuenteEnergia>
                                    <escConMedidaFuenteEnergia>',FuenteEnergia mappedCodigos keys asOrderedCollection randomPeek,'</escConMedidaFuenteEnergia>
                                    <escSinMedidaPrecioEnergetico>', (#(100 200 300 400 500 600 700) randomPeek) printString,'</escSinMedidaPrecioEnergetico>
                                    <escConMedidaPrecioEnergetico>', (#(100 200 300 400 500 600 700) randomPeek) printString,'</escConMedidaPrecioEnergetico>
                                    <escSinMedidaUyuUnidadFisica>UYU/tonelada</escSinMedidaUyuUnidadFisica>
                                    <escConMedidaUyuUnidadFisica>UYU/tonelada</escConMedidaUyuUnidadFisica>
                                    <escSinMedidaConsumoEnergia>', (#(120 220 320 450 550 660 780) randomPeek) printString,'</escSinMedidaConsumoEnergia>
                                    <escConMedidaConsumoEnergia>', (#(142 258 330 498 556 690 790) randomPeek) printString,'</escConMedidaConsumoEnergia>
                                    <escSinMedidaUnidadFisica>tonelada</escSinMedidaUnidadFisica>
                                    <escConMedidaUnidadFisica>tonelada</escConMedidaUnidadFisica>
                                    <escSinMedidaValorTepAnio>102.0</escSinMedidaValorTepAnio>
                                    <escConMedidaValorTepAnio>131.404</escConMedidaValorTepAnio>
                                    <escSinMedidaValorUyu>120000</escSinMedidaValorUyu>
                                    <escConMedidaValorUyu>98000</escConMedidaValorUyu>
                                    <escSinMedidaEmisionCO2>457.034664</escSinMedidaEmisionCO2>
                                    <escConMedidaEmisionCO2>536.51070564</escConMedidaEmisionCO2>
                                </section-2-iteration>
                                <section-2-iteration>
                                    <escSinMedidaFuenteEnergia>', FuenteEnergia mappedCodigos keys asOrderedCollection randomPeek,'</escSinMedidaFuenteEnergia>
                                    <escConMedidaFuenteEnergia>', FuenteEnergia mappedCodigos keys asOrderedCollection randomPeek,'</escConMedidaFuenteEnergia>
                                    <escSinMedidaPrecioEnergetico>', (#(100 200 300 400 500 600 700) randomPeek) printString,'</escSinMedidaPrecioEnergetico>
                                    <escConMedidaPrecioEnergetico>', (#(100 200 300 400 500 600 700) randomPeek) printString,'</escConMedidaPrecioEnergetico>
                                    <escSinMedidaUyuUnidadFisica>UYU/tonelada</escSinMedidaUyuUnidadFisica>
                                    <escConMedidaUyuUnidadFisica>UYU/tonelada</escConMedidaUyuUnidadFisica>
                                    <escSinMedidaConsumoEnergia>', (#(120 220 320 450 550 660 780) randomPeek) printString,'</escSinMedidaConsumoEnergia>
                                    <escConMedidaConsumoEnergia>', (#(142 258 330 498 556 690 790) randomPeek) printString,'</escConMedidaConsumoEnergia>
                                    <escSinMedidaUnidadFisica>tonelada</escSinMedidaUnidadFisica>
                                    <escConMedidaUnidadFisica>metros cúbicos</escConMedidaUnidadFisica>
                                    <escSinMedidaValorTepAnio>102.0</escSinMedidaValorTepAnio>
                                    <escConMedidaValorTepAnio>131.404</escConMedidaValorTepAnio>
                                    <escSinMedidaValorUyu>120000</escSinMedidaValorUyu>
                                    <escConMedidaValorUyu>98000</escConMedidaValorUyu>
                                    <escSinMedidaEmisionCO2>30</escSinMedidaEmisionCO2>
                                    <escConMedidaEmisionCO2>40</escConMedidaEmisionCO2>
                                </section-2-iteration>
                            </section-2>
                        </section-1-iteration>
                    </section-1>
                </form>'