cache
validNames

	^#('Aserrín' 'Bagazo' 'Biodiesel' 'Bioetanol' 'Carbón mineral' 'Carbón vegetal' 'Cáscara de arroz' 'Cáscara de girasol' 'Casullo de cebada' 'Chips' 'Coque de carbón' 'Coque de petróleo' 'Coque de petróleo importado' 'Electricidad de la red' 'Fuel oil calefacción' 'Fuel oil intermedio' 'Fuel oil pesado' 'Gas natural' 'Gasoil 10S' 'Gasoil 50S' 'Gasolina aviación 100/130' 'Gasolina premium 97 30SP' 'Gasolina super 95 30SP' 'GLP' 'Leña' 'Licor negro' 'Pellets de madera' 'Propano' 'Queroseno' 'Residuos forestales' 'Supergas' )