other
populateCache

	self new 
		nombre: 'Línea de asistencia para eficiencia energética (LAEE)';
		descripcion: 'Apoya a los proyectos en la fase de diagnóstico e identificación de las potenciales medidas de eficiencia energética.';
		addToCache.

	self new 
		nombre: 'Certificados de eficiencia energética (CEE)';
		descripcion: 'Permiten a la empresa obtener un ingreso monetario por las medidas de eficiencia energética implementadas.';
		addToCache.

	self new 
		nombre: 'Premio Nacional de Eficiencia Energética';
		descripcion: 'Busca dar visibilidad y difusión a los proyectos de eficiencia.';
		addToCache.

	self new 
		nombre: 'Categorización de las ESCOs (empresas de servicios energéticos)';
		descripcion: 'Promueve el desempeño eficiente de las ESCO mediante en un sistema claro, transparente y sencillo de implementar y monitorear';
		addToCache.