other
validNames

	^OrderedCollection new 
		add: ('bombeo-de-agua' -> 'Bombeo de Agua');
		add: ('alumbrado-Publico' -> 'Alumbrado Público');
		add: ('calefaccion-de-ambientes' -> 'Calefacción de ambientes');
		add: ('calentamiento-de-agua' -> 'Calentamiento de Agua');
		add: ('calor-directo' -> 'Calor directo');
		add: ('coccion' -> 'Cocción');
		add: ('cogeneracion' -> 'Cogeneración');
		add: ('conservacion-de-alimentos' -> 'Conservación de alimentos');
		add: ('frio-de-proceso' -> 'Frío de Proceso');
		add: ('fuerza-motriz-fija' -> 'Fuerza Motriz fija');
		add: ('generacion-de-electricidad' -> 'Generación de electricidad');
		add: ('generacion-de-vapor' -> 'Generación de vapor');
		add: ('iluminacion' -> 'Iluminación');
		add: ('riego' -> 'Riego');
		add: ('transporte' -> 'Transporte');
		add: ('transporte-interno' -> 'Transporte interno');
		add: ('ventilación-refrigeracion-de-ambientes' -> 'Ventilación y Refrigeración de Ambientes');
		add: ('otros-usos' -> 'Otros usos');
		yourself