other
allCss

	^'
.medida-comparison-title {
	margin-bottom: 15px;
}
.media-comparision-common-data {
	display: inline-flex;
	padding: 5px;
	background-color: darkgray;
	border-radius: 5px;
	margin-right: 10px;
}
.media-comparision-key {
	margin-right: 15px;
}
.media-comparision-value {
	margin-right: 10px;
	background-color: gray;
    padding: 3px;
    border-radius: 5px;
}
.medida-comparison {
	margin-top: 20px;
	background-color: lightgray;
	margin: 15px;
	padding: 10px;
	border-radius: 10px;
}
.medida-comparison legend {
	color: black;
	font-size: larger;
	margin-bottom: 10px;
	text-align: center;
}
.medida-comparison .title {
	display: inline-flex;
	margin-left: 10px;
	width: 200px;
	color: darkblue;
}
.medida-comparison .item {
	display: inline-flex;
	margin-left: 10px;
	width: 200px;
	margin: 5px;
	padding: 2px;
}
.medida-comparison .sin-medida {
	padding: 2px;
	background-color: ivory;
	border-radius: 5px;
}
.medida-comparison .con-medida {
	padding: 2px;
	background-color: ghostwhite;
	border-radius: 5px;
}
.medida-comparison .diferencia {
	padding: 2px;
	background-color: white;
	border-radius: 5px;
}
.boton-cerrar {}
.boton-cerrar fieldset {
	border: none;
}
.boton-cerrar fieldset input {
	border-radius: 10px;
	float: right;
}
'